import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        {children}
        <Image
          src="/bg-watermark.png"
          alt="Watermark"
          width={1000}
          height={1000}
          className="absolute bottom-0 right-0 opacity-10 pointer-events-none"
        />
      </body>
    </html>
  );
}
